# # traefik/traefik-values.yaml
# deployment:
#   replicas: 1

# providers:
#   kubernetesIngress:
#     publishedService:
#       enabled: true

# ports:
#   web:
#     redirectTo: websecure
#   websecure:
#     tls:
#       enabled: true

# ingressRoute:
#   dashboard:
#     enabled: true

# service:
#   type: LoadBalancer
# #  spec:
# #    loadBalancerIP: 10.64.13.210
#   spec: {}





# traefik/traefik-values.yaml
deployment:
  replicas: 1

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      # Désactive certResolver car on utilise mkcert
      # certResolver: myresolver

# DÉSACTIVE Let's Encrypt - on utilise mkcert
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: ton-email@exemple.com
#       storage: /data/acme.json
#       httpChallenge:
#         entryPoint: web

ingressRoute:
  dashboard:
    enabled: true

service:
  type: LoadBalancer